### ISSUE TITLE
[Help] How do I skip the download procedure of the apps?

### ISSUE THREAD

**Issue by pitsi** [canneverbe/Ketarin#10]
As the title says, I would like to know if there is a way for ketarin to skip the download and use a setup file that is already located in the drive.

I already have and maintain a set of installers in my drive, so I would like ketarin to use them and not download anything if possible. Also, some apps, e.g. firefox or winrar, have different installers for every locale and, although I am personally ok with ketarin downloading and installing the english ones, almost all of my users prefer the greek ones because this is the language they speak and the language their windows is set to.

Thank you in advance.

**Comment by floele** [comment]
I think downloading is optional, did you check https://wiki.ketarin.org/index.php/Setup_instructions ? Otherwise you should probably ask in our forum (https://forum.cdburnerxp.se/), there are quite a few experts there to help :-)

**Comment by pitsi** [comment]
I will look that up... again, but I think it does not mention what I ask for. Let's call it "offline installation" for short.

**Comment by ekardian** [comment]
> 
> 
> I will look that up... again, but I think it does not mention what I ask for. Let's call it "offline installation" for short.

there are a post in the forum with a solution for offline install, but u need made a hack in the database, and replicate the relative target of your apps, was tested and working, in a few days that post w'll be updated with a other scenario for an offline install

https://ketarin.org/forum/topic/4323-trick-for-offline-ketarin-working/

**Comment by pitsi** [comment]
That seems easy. I have used sqlitebrowser in the past, so I am familiar with it. I will check it and report back.
Meanwhile, I somehow managed to make it skip the download by placing the setup file (for winrar) and enabling some of the option(s) in the main window.
