### ISSUE TITLE
Is native version check available

### ISSUE THREAD

**Issue by Youxikong** [canneverbe/Ketarin#20]
I suggest to check native version, strore the value and compare the online version to avoid re-downloading the same file.

**Comment by shawnkhall** [comment]
This capability already exists. You'll need to identify where on the website the version number is exposed then store that within a variable (assume "version") then on the `Advanced settings` tab within the `Use the following variable as indicator for changes` field set the value to "version".

**Comment by Youxikong** [comment]
> This capability already exists. You'll need to identify where on the website the version number is exposed then store that within a variable (assume "version") then on the `Advanced settings` tab within the `Use the following variable as indicator for changes` field set the value to "version".

I know this way. But if the local file deleted, Ketarin will download again whenever "version" changes or not.
I want to check registry or local files' properties and store the value to another variable (maybe "Installed Version"). Then I can compare it with "version".

**Comment by shawnkhall** [comment]
If you don't want it to download a file that has been removed locally then check the box under `Advanced settings`, `Ignore file information (do not re-download if file is missing)`. This is **exactly** the purpose of that option.

**Comment by Youxikong** [comment]
Yes, it is exactly what I want. But I'm confused it didn't work last time setting as this. Maybe I changed other things.
Thanks for your help.
