### ISSUE TITLE
Controls of form overlapped

### ISSUE THREAD

**Issue by sagasm** [canneverbe/Ketarin#24]
Ketarin 1.8.11.0:
![image](https://github.com/canneverbe/Ketarin/assets/14829950/ede24488-dff1-4543-8105-d22d7680cb10)
So, what is the original font for all the controls:
![image](https://github.com/canneverbe/Ketarin/assets/14829950/d60ce208-5460-44d9-8c38-1770cd1e082c)

**Comment by shawnkhall** [comment]
I suspect this is from your environment. The only fonts referenced in the code or resources are Verdana, Microsoft Sans Serif and Courier New. What platform and development environment are you using?

**Comment by sagasm** [comment]
OS: win10 x64 22H2:
![image](https://github.com/canneverbe/Ketarin/assets/14829950/4c7871fb-22ba-4d79-ad5c-f83e60a24a72)
![image](https://github.com/canneverbe/Ketarin/assets/14829950/27dd21db-ef19-4700-9116-650c9b3cd6a2)
![image](https://github.com/canneverbe/Ketarin/assets/14829950/79835027-9c75-4ae6-aa04-51c87db9c892)
IDE: VS2022

**Comment by sagasm** [comment]
I think it is because my registry entry [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\GRE_Initialize\GUIFont.Facename] is SimSun.
